spring:
  oracle:
    username: system
    password: oracle
    jdbcUrl: jdbc:oracle:thin:@127.0.0.1:1521:XE/lab_oracle
  mysql:
    username: root
    password:
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/lab_mysql
  mssql:
    username: sa
    password:
    jdbcUrl: jdbc:sqlserver://127.0.0.1:1433/lab_mssql
  postgresql:
    username: root
    password:
    jdbcUrl: jdbc:postgresql://127.0.0.1:5432/lab_postgresql