spring:
  oracle:
    username: system
    password: oracle
    jdbc-url: jdbc:oracle:thin:@127.0.0.1:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
  mysql:
    username: root
    password:
    jdbc-url: jdbc:mysql://127.0.0.1:3306/LAB
    driver-class-name: com.mysql.cj.jdbc.Driver
  mssql:
    username: sa
    password:
    jdbc-url: jdbc:sqlserver://127.0.0.1:1433;encrypt=false;DatabaseName=LAB
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  postgresql:
    username: root
    password:
    jdbc-url: jdbc:postgresql://127.0.0.1:5432/LAB
    driver-class-name: org.postgresql.Driver

  main:
    allow-bean-definition-overriding: true